version: '3'

services:
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  caddy:
    image: caddy:alpine
    volumes:
      - ./html:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "9000:80"

volumes:
  db-data:
