version: '3'

services:
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d:ro

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
