version: '3'

services:
  db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql


  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["node", "entry.js"]
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=No-Taps
      - DATABASE_PASSWORD=Taps
      - DATABASE_NAME=mydb


volumes:
  db-data:
